### ISSUE TITLE
Lammps processing error atom index out of range

### ISSUE THREAD

**Issue by JFRudzinski** [nomad-coe/atomistic-parsers#90]
From 1xyz test:

```
"root":{
"errors":string"parser failed with exception"
"event":string"process failed"
"proc":string"Entry"
"process":string"process_entry"
"process_worker_id":string"Ub5K99TxQripuoE6OKZAdg"
"parser":string"parsers/lammps"
"error":string"index 500 is out of bounds for axis 0 with size 500"
"step":string"parsers/lammps"
"logger":string"nomad.processing"
"exception":string"Traceback (most recent call last): File "/home/jfrudzinski/work/soft/nomad/nomad/processing/data.py", line 1469, in parsing parser.parse( File "/home/jfrudzinski/work/soft/nomad/nomad/parsing/parser.py", line 460, in parse self.mainfile_parser.parse(mainfile, archive, logger) File "/home/jfrudzinski/work/soft/nomad/dependencies/parsers/atomistic/atomisticparsers/lammps/parser.py", line 1730, in parse self.parse_system() File "/home/jfrudzinski/work/soft/nomad/dependencies/parsers/atomistic/atomisticparsers/lammps/parser.py", line 1458, in parse_system elements = atoms_elements[sec_molecule.atom_indices] IndexError: index 500 is out of bounds for axis 0 with size 500"
"timestamp":string"2024-01-24 12:14.49"
"level":string"ERROR"
}
Traceback (most recent call last):
  File "/home/jfrudzinski/work/soft/nomad/nomad/processing/data.py", line 1469, in parsing
    parser.parse(
  File "/home/jfrudzinski/work/soft/nomad/nomad/parsing/parser.py", line 460, in parse
    self.mainfile_parser.parse(mainfile, archive, logger)
  File "/home/jfrudzinski/work/soft/nomad/dependencies/parsers/atomistic/atomisticparsers/lammps/parser.py", line 1730, in parse
    self.parse_system()
  File "/home/jfrudzinski/work/soft/nomad/dependencies/parsers/atomistic/atomisticparsers/lammps/parser.py", line 1458, in parse_system
    elements = atoms_elements[sec_molecule.atom_indices]
IndexError: index 500 is out of bounds for axis 0 with size 500
```

**Comment by JFRudzinski** [comment]
@ladinesa I get the above error when I process my example in the GUI, but when I parse it just in python `sec_molecule.atom_indices` is maximum `[499]` instead of `[500]` as expected. I will try to investigate further, I just wanted to ask if you can imagine any reason that I am getting a different behavior in the GUI and in python?

**Comment by ladinesa** [comment]
> GUI

the error seems to be coming solely from the parser. i was thinking that the parser version is not the same.

**Comment by JFRudzinski** [comment]
ok thanks, I will investigate
